### ISSUE TITLE
Pin icons do not reset after first attempt.

### ISSUE THREAD

**Issue by joe-replin** [cgkineo/adapt-ppq#4]
After making a first attempt, the pins do not reset. While making selections on the 2nd attempt, the pins remain as check marks and crosses in the order you placed them from the first attempt. The pins will change again to new check marks and crosses after selecting submit on the 2nd attempt.

**Comment by chris-steele** [comment]
@joe-replin Hi Joe, this was fixed in the rewrite.

**Comment by joe-replin** [comment]
Great! Thank you Chris.
